language: python
python:
  - "3.8"

before_install:
  - python3 -m pip install poetry

install:
  - make install

env:
  global:
    - CC_TEST_REPORTER_ID=5d718a2462d7e3cc9f3aef1f5b1be5ab0e259a79f50bd093642f4b29a567c925

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test-coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
