name: TestLint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        poetry self update
        poetry install
    - name: Lint with flake8 (wemake-python-styleguide)
      run: |
        poetry run flake8 airflight tests
    - name: Test with pytest
      run: |
        poetry run pytest
